project_id = "dfhanacsmsvvkpunurnp"

[functions.create-payment]
verify_jwt = false

[functions.create-subscription]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.create-campaigns]
verify_jwt = false

[functions.automation-post]
verify_jwt = false

[functions.x-daily-post]
verify_jwt = false
